# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-03 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/upload/food', verbose_name='美食')),
                ('time', models.DateField(verbose_name='发表时间')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
            ],
            options={
                'verbose_name': '美食',
                'verbose_name_plural': '美食',
                'db_table': 'food',
            },
        ),
        migrations.CreateModel(
            name='Happiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/upload/happiness', verbose_name='心情')),
                ('time', models.DateField(verbose_name='发表时间')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
            ],
            options={
                'verbose_name': '心情',
                'verbose_name_plural': '心情',
                'db_table': 'happiness',
            },
        ),
        migrations.CreateModel(
            name='Landscape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/upload/landscape', verbose_name='风景')),
                ('time', models.DateField(verbose_name='发表时间')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
            ],
            options={
                'verbose_name': '风景',
                'verbose_name_plural': '风景',
                'db_table': 'landscape',
            },
        ),
        migrations.CreateModel(
            name='Life',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/upload/life', verbose_name='生活')),
                ('time', models.DateField(verbose_name='发表时间')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
            ],
            options={
                'verbose_name': '生活',
                'verbose_name_plural': '生活',
                'db_table': 'life',
            },
        ),
    ]
